
["World Settings"]
	#Do you want the game to crash?
	"Game crashes" = true
	#Rebalences the game if you have The Broken Script installed
	"TBS mode" = false
	#This is a challenge for the best of the best. Makes changes to all entities to make them 10 times worse
	Hardmode = false
	#Do you want random structures to appear?
	"Disable random structures" = false
	#Toggling this will make events happen much faster
	"Fast events" = false
	#Do you want the entities to break blocks?
	Destruction = true
	#Reduces the chase length from 1 minute to 30 seconds
	"Reduce chase length" = false
	#Do you want Nothing_left to talk?
	Nothing_left = true

["Player Settings"]
	#Do you want the game to ban you from your world? (THIS ONLY HAPPENS IF YOUR DOING SOMETHING VERY SECRETIVE)
	Banning = true

