
#Horror System Settings
[horror]
	#Enable horror effects
	horrorEnabled = true
	#Reset horror progression on player login
	resetOnLogin = false
	#Time in minutes between horror stages. Lower values = faster progression.
	#Range: 1 ~ 1440
	timeBetweenStages = 30
	#Duration of each stage in minutes before progressing to next stage
	#Range: 1 ~ 1440
	stageDuration = 30
	#Base frequency of horror events (0.0-1.0). Higher values = more frequent events.
	#Range: 0.0 ~ 1.0
	eventFrequency = 0.35
	#Synchronize horror events across all players in multiplayer to ensure a shared experience. IMPORTANT: Required for Protocol_37 and Iteration entities to spawn visibly in multiplayer.
	syncMultiplayerEvents = true
	#Dynamically scale event frequencies based on player count in multiplayer. When enabled, the frequency of per-player events will be reduced as more players join to prevent event overload.
	dynamicMultiplayerScaling = true
	#Controls how aggressively the event frequency scales down with more players. Lower values = more aggressive scaling (0.5-1.0)
	#Range: 0.5 ~ 1.0
	multiplayerScalingFactor = 0.75
	#Minimum time in seconds between horror events for a single player. Prevents event spam.
	#Range: 0 ~ 600
	globalEventCooldown = 45
	#Minimum number of horror events a player should experience during each stage before progression. Set to 0 to disable.
	#Range: 0 ~ 30
	minimumEventsPerStage = 5
	#Enable community-inspired entities. These include Protocol 37's invisible form, the distant stalker, mining entity, and angry Protocol 37.
	enableCommunityEntities = true
	#Chance (1 in X) for the distant stalker entity to spawn
	#Range: 1 ~ 10000
	distantStalkerSpawnChance = 50
	#Chance (1 in X) for Protocol 37 to transform into its angry form
	#Range: 1 ~ 100
	protocol37TransformChance = 5

	#ARG and Endgame Settings
	[horror.argAndEndgame]
		#Enable the endgame sequence that can 'erase' the world. When disabled, the endgame sequence can't be triggered.
		enableEndgameSequence = true
		#Use ARG-style sounds (distorted, eerier) instead of vanilla sound effects. Creates a more unsettling atmosphere.
		useArgStyleSounds = true
		#Controls the intensity of ARG sound effects (1-5). Higher values create more distorted and unsettling sounds.
		#Range: 1 ~ 5
		argSoundIntensity = 3

